### ISSUE TITLE
How to pass blog article (item) by direct navigation or refresh.

### ISSUE THREAD

**Issue by hyperpress** [hyperpress/pressmedics#15]
Determine best method for passing blog list item to full article update route location.

**Comment by hyperpress** [comment]
Using the current Redux actions and reducer logic for articles list works as expected, and selecting a list item correctly uses the articles list item json object in rendering the detailed article. However, when attempting to refresh an article or navigate directly to an article by URL, it fails with an error of undefined on applicable fields. 

1. (Works as expected) Here is a screenshot of the blog articles list JSON object returned by actions/articles:

![articles-list-redux-json-output](https://user-images.githubusercontent.com/25212653/45046656-78710800-b03c-11e8-9c7c-27f26147cdf0.png)

2. (Works as expected) Here is a screenshot of the article item JSON returned when navigated to by clicking on a blog list item:

![article-redux-json-output-clicked-blog-list-item](https://user-images.githubusercontent.com/25212653/45046820-eddcd880-b03c-11e8-843f-fc48dc209ce4.png)

3. (Fails to render output with undefined error) Screenshot of blog article JSON output when navigating directly to item by URL or when refreshed from clicked blog list item:

![article-redux-json-output-onrefresh-or-direct-navigation](https://user-images.githubusercontent.com/25212653/45046984-6479d600-b03d-11e8-915c-19fa20d3dee0.png)

The error from 3 is:
`
Exception
:
TypeError: Cannot read property 'title' of undefined at HTMLElement.render (https://localhost:6443/src/components/ts-article.js:41:24) at HTMLElement.update (https://localhost:6443/node_modules/@polymer/lit-element/lit-element.js:40:36) at HTMLElement._flush (https://localhost:6443/node_modules/@polymer/lit-element/lib/updating-element.js:427:12) at HTMLElement.invalidate (https://localhost:6443/node_modules/@polymer/lit-element/lib/updating-element.js:404:12)
author
:
undefined
categories
:
undefined
date
:
undefined
item
:
undefined
slug
:
undefined
this
:
ts-article.page
thumbnail
:
undefined
title
:
undefined
_data
:
undefined
_lastVisitedListPage
:
undefined
_showOffline
:
false`

**Comment by hyperpress** [comment]
@captaincodeman assisted with fix by pointing out there there was no conditional check to prevent render from firing if data not available from fetch. Added simple condition check for !_data and loader text until it is.
